"use strict";
const { spawn } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const { VargaRpc } = require("./rpc");

const KNOWN_NODES = [
  "217.154.93.20:29666",
  "212.132.80.39:29666",
  "31.70.81.5:29666"
];

const CORE_ARGS = Object.freeze(["-printtoconsole=0"]);

function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }

class CoreManager {
  constructor({ dataDir, configFile, coreDir }) {
    this.dataDir = dataDir;
    this.configFile = configFile;
    this.coreDir = coreDir;
    this.cookieFile = path.join(dataDir, ".cookie");
    this.rpc = new VargaRpc({ cookieFile: this.cookieFile, port: 29667 });
    this.child = null;
    this.ownsProcess = false;
    this.startPromise = null;
    this.lastExit = null;
  }

  ensureConfig() {
    fs.mkdirSync(this.dataDir, { recursive: true });
    if (fs.existsSync(this.configFile)) return { created: false, file: this.configFile };
    const config = [
      "# Generated by VargaMesh Desktop v0.1.1",
      "# P2P is public; RPC stays localhost-only.",
      "server=1",
      "listen=1",
      "bind=0.0.0.0:29666",
      "rpcbind=127.0.0.1",
      "rpcallowip=127.0.0.1",
      "rpcport=29667",
      ...KNOWN_NODES.map(n => `addnode=${n}`),
      ""
    ].join("\r\n");
    fs.writeFileSync(this.configFile, config, { encoding: "utf8", mode: 0o600 });
    return { created: true, file: this.configFile };
  }

  executable() {
    const exe = path.join(this.coreDir, "vargameshd.exe");
    if (!fs.existsSync(exe)) throw new Error(`Bundled VargaMesh Core not found: ${exe}`);
    return exe;
  }

  async isRpcReady() {
    try { await this.rpc.call("getblockchaininfo", [], "", 1500); return true; }
    catch (_) { return false; }
  }

  launchArgs() {
    return [
      `-datadir=${this.dataDir}`,
      `-conf=${this.configFile}`,
      ...CORE_ARGS
    ];
  }

  writeLaunchDiagnostic(args) {
    try {
      const log = path.join(this.dataDir, "desktop-runtime.log");
      fs.appendFileSync(log, `${new Date().toISOString()} core-start ${JSON.stringify(args)}\n`, "utf8");
    } catch (_) {}
  }

  async start() {
    this.ensureConfig();
    if (await this.isRpcReady()) return { running: true, external: !this.ownsProcess };
    if (this.startPromise) return this.startPromise;
    this.startPromise = this._startOwned().finally(() => { this.startPromise = null; });
    return this.startPromise;
  }

  async _startOwned() {
    if (this.child && !this.child.killed) {
      const deadline = Date.now() + 60_000;
      while (Date.now() < deadline) {
        if (await this.isRpcReady()) return { running: true, external: false };
        if (!this.child) break;
        await sleep(500);
      }
      throw new Error("VargaMesh Core process is running but RPC did not become ready.");
    }

    const exe = this.executable();
    const args = this.launchArgs();
    this.lastExit = null;
    this.writeLaunchDiagnostic(args);
    this.child = spawn(exe, args, {
      cwd: this.coreDir,
      windowsHide: true,
      stdio: "ignore"
    });
    this.ownsProcess = true;
    const launched = this.child;
    launched.once("exit", (code, signal) => {
      this.lastExit = { code, signal, at: new Date().toISOString() };
      if (this.child === launched) this.child = null;
      this.ownsProcess = false;
    });

    const deadline = Date.now() + 60_000;
    while (Date.now() < deadline) {
      if (await this.isRpcReady()) return { running: true, external: false };
      if (!this.child) {
        const suffix = this.lastExit ? ` Exit code: ${this.lastExit.code ?? "null"}, signal: ${this.lastExit.signal ?? "none"}.` : "";
        throw new Error(`VargaMesh Core exited before RPC became ready.${suffix} Check debug.log in the VargaMesh data directory.`);
      }
      await sleep(500);
    }
    throw new Error("VargaMesh Core did not become RPC-ready within 60 seconds. Check debug.log in the VargaMesh data directory.");
  }

  async stop() {
    if (!(await this.isRpcReady())) return { stopped: true };
    if (!this.ownsProcess) return { stopped: false, external: true };
    try { await this.rpc.call("stop", [], "", 5000); } catch (_) {}
    const deadline = Date.now() + 12_000;
    while (this.child && Date.now() < deadline) await sleep(250);
    if (this.child) {
      try { this.child.kill(); } catch (_) {}
    }
    return { stopped: true };
  }

  async nodeStatus() {
    const chain = await this.rpc.call("getblockchaininfo");
    const net = await this.rpc.call("getnetworkinfo");
    return {
      running: true,
      chain: chain.chain,
      blocks: chain.blocks,
      headers: chain.headers,
      bestblockhash: chain.bestblockhash,
      verificationprogress: chain.verificationprogress,
      initialblockdownload: chain.initialblockdownload,
      size_on_disk: chain.size_on_disk,
      connections: net.connections,
      connections_in: net.connections_in,
      connections_out: net.connections_out,
      subversion: net.subversion,
      protocolversion: net.protocolversion,
      localservicesnames: net.localservicesnames || []
    };
  }
}

module.exports = { CoreManager, KNOWN_NODES, CORE_ARGS };
