"use strict";

const { spawn } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");
const { VargaRpc } = require("./rpc");

const KNOWN_NODES = Object.freeze([
  "217.154.93.20:29666",
  "212.132.80.39:29666",
  "31.70.81.5:29666"
]);
const CORE_ARGS = Object.freeze(["-printtoconsole=0"]);

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

function windowsExitHint(code) {
  const n = Number(code);
  if (!Number.isFinite(n)) return "";
  const hex = `0x${(n >>> 0).toString(16).toUpperCase().padStart(8, "0")}`;
  if ((n >>> 0) === 0xC0000135) {
    return `${hex} STATUS_DLL_NOT_FOUND: a required Windows runtime DLL could not be resolved.`;
  }
  return hex;
}

class CoreManager {
  constructor({ dataDir, configFile, coreDir }) {
    this.dataDir = dataDir;
    this.configFile = configFile;
    this.coreDir = coreDir;
    this.cookieFile = path.join(dataDir, ".cookie");
    this.rpc = new VargaRpc({ cookieFile: this.cookieFile, port: 29667 });
    this.child = null;
    this.ownsProcess = false;
    this.startPromise = null;
    this.lastExit = null;
  }

  ensureConfig() {
    fs.mkdirSync(this.dataDir, { recursive: true });
    if (fs.existsSync(this.configFile)) return { created: false, file: this.configFile };
    const config = [
      "# Generated by VargaMesh Desktop v0.2.1",
      "# P2P is public; JSON-RPC is localhost-only.",
      "server=1",
      "listen=1",
      "bind=0.0.0.0:29666",
      "rpcbind=127.0.0.1",
      "rpcallowip=127.0.0.1",
      "rpcport=29667",
      ...KNOWN_NODES.map(node => `addnode=${node}`),
      ""
    ].join("\r\n");
    fs.writeFileSync(this.configFile, config, { encoding: "utf8", mode: 0o600 });
    return { created: true, file: this.configFile };
  }

  executable() {
    const exe = path.join(this.coreDir, "vargameshd.exe");
    if (!fs.existsSync(exe)) throw new Error(`Bundled VargaMesh Core not found: ${exe}`);
    return exe;
  }

  launchArgs() {
    return [`-datadir=${this.dataDir}`, `-conf=${this.configFile}`, ...CORE_ARGS];
  }

  writeDiagnostic(event, data = {}) {
    try {
      const safe = { ...data };
      delete safe.password;
      delete safe.passphrase;
      delete safe.cookie;
      fs.appendFileSync(path.join(this.dataDir, "desktop-runtime.log"), `${new Date().toISOString()} ${event} ${JSON.stringify(safe)}\n`, "utf8");
    } catch (_) {}
  }

  async isRpcReady() {
    try { await this.rpc.call("getblockchaininfo", [], "", 1500); return true; }
    catch (_) { return false; }
  }

  async start() {
    this.ensureConfig();
    if (await this.isRpcReady()) return { running: true, external: !this.ownsProcess };
    if (this.startPromise) return this.startPromise;
    this.startPromise = this._startOwned().finally(() => { this.startPromise = null; });
    return this.startPromise;
  }

  async _startOwned() {
    const exe = this.executable();
    const args = this.launchArgs();
    this.lastExit = null;
    const env = { ...process.env };
    if (process.platform === "win32") {
      const win = env.SystemRoot || env.WINDIR || "C:\\Windows";
      const requiredPath = [
        this.coreDir,
        path.join(win, "System32"),
        path.join(win, "System32", "Wbem"),
        path.join(win, "System32", "WindowsPowerShell", "v1.0")
      ];
      const current = env.Path || env.PATH || "";
      env.Path = [...requiredPath, current].filter(Boolean).join(";");
      env.PATH = env.Path;
    }
    this.writeDiagnostic("core-start", { args, exe, cwd: this.coreDir });
    try {
      this.child = spawn(exe, args, { cwd: this.coreDir, windowsHide: true, stdio: "ignore", env });
    } catch (err) {
      this.writeDiagnostic("core-spawn-error", { message: String(err?.message || err), code: err?.code || null });
      throw err;
    }
    this.ownsProcess = true;
    const launched = this.child;
    launched.once("error", err => {
      this.writeDiagnostic("core-process-error", { message: String(err?.message || err), code: err?.code || null });
    });
    launched.once("exit", (code, signal) => {
      this.lastExit = { code, signal, hint: windowsExitHint(code), at: new Date().toISOString() };
      this.writeDiagnostic("core-exit", this.lastExit);
      if (this.child === launched) this.child = null;
      this.ownsProcess = false;
    });

    const deadline = Date.now() + 75_000;
    while (Date.now() < deadline) {
      if (await this.isRpcReady()) return { running: true, external: false };
      if (!this.child) {
        const suffix = this.lastExit
          ? ` Exit code: ${this.lastExit.code ?? "null"}${this.lastExit.hint ? ` (${this.lastExit.hint})` : ""}.`
          : "";
        throw new Error(`VargaMesh Core exited before RPC became ready.${suffix}`);
      }
      await sleep(500);
    }
    throw new Error("VargaMesh Core did not become RPC-ready within 75 seconds.");
  }

  async stop() {
    if (!(await this.isRpcReady())) return { stopped: true };
    if (!this.ownsProcess) return { stopped: false, external: true };
    try { await this.rpc.call("stop", [], "", 5000); } catch (_) {}
    const deadline = Date.now() + 15_000;
    while (this.child && Date.now() < deadline) await sleep(250);
    if (this.child) { try { this.child.kill(); } catch (_) {} }
    return { stopped: true };
  }

  async nodeStatus() {
    const [chain, net] = await Promise.all([
      this.rpc.call("getblockchaininfo"),
      this.rpc.call("getnetworkinfo")
    ]);
    return {
      running: true,
      chain: chain.chain,
      blocks: chain.blocks,
      headers: chain.headers,
      bestblockhash: chain.bestblockhash,
      difficulty: chain.difficulty,
      verificationprogress: chain.verificationprogress,
      initialblockdownload: chain.initialblockdownload,
      size_on_disk: chain.size_on_disk,
      connections: net.connections,
      connections_in: net.connections_in,
      connections_out: net.connections_out,
      subversion: net.subversion,
      protocolversion: net.protocolversion,
      networkactive: net.networkactive,
      localservicesnames: net.localservicesnames || []
    };
  }
}

module.exports = { CoreManager, KNOWN_NODES, CORE_ARGS };
