"use strict";

const { contextBridge, ipcRenderer } = require("electron");

const call = (channel, payload = {}) => ipcRenderer.invoke(channel, payload);

contextBridge.exposeInMainWorld("vmesh", Object.freeze({
  appInfo: () => call("app:info"),
  getSettings: () => call("settings:get"),
  updateSettings: patch => call("settings:update", patch),
  startCore: () => call("core:start"),
  stopCore: () => call("core:stop"),
  coreStatus: () => call("core:status"),
  mempool: () => call("core:mempool"),
  mining: () => call("core:mining"),
  peers: () => call("core:peers"),
  marketQuote: () => call("market:quote"),
  contacts: () => call("contact:list"),
  saveContact: entry => call("contact:save", entry),
  deleteContact: id => call("contact:remove", { id }),
  resolveRecipient: target => call("recipient:resolve", { target }),
  listWallets: () => call("wallet:list"),
  createWallet: data => call("wallet:create", data),
  generateHdWallet: (words = 24) => call("wallet:hdGenerate", { words }),
  createHdWallet: data => call("wallet:hdCreate", data),
  saveRecoveryPhrase: data => call("wallet:saveRecoveryPhrase", data),
  restoreHdWallet: data => call("wallet:hdRestore", data),
  loadWallet: name => call("wallet:load", { name }),
  unloadWallet: name => call("wallet:unload", { name }),
  walletSummary: wallet => call("wallet:summary", { wallet }),
  transactions: (wallet, count = 50, skip = 0) => call("wallet:transactions", { wallet, count, skip }),
  exportTransactions: wallet => call("wallet:exportCsv", { wallet }),
  unspent: wallet => call("wallet:unspent", { wallet }),
  newAddress: (wallet, label = "") => call("wallet:newaddress", { wallet, label }),
  validateAddress: address => call("wallet:validate", { address }),
  estimateFee: (target = 6) => call("wallet:fee", { target }),
  unlockWallet: (wallet, passphrase, seconds) => call("wallet:unlock", { wallet, passphrase, seconds }),
  lockWallet: wallet => call("wallet:lock", { wallet }),
  send: data => call("wallet:send", data),
  vmtPortfolio: wallet => call("vmt:portfolio", { wallet }),
  vmtDirectory: query => call("vmt:directory", { query }),
  vmtTokenDetail: tokenId => call("vmt:tokenDetail", { tokenId }),
  vmtTokenLogo: tokenId => call("vmt:tokenLogo", { tokenId }),
  vmtPrepare: (wallet, request) => call("vmt:prepare", { wallet, request }),
  vmtBroadcast: (wallet, candidateId) => call("vmt:broadcast", { wallet, candidateId }),
  backupWallet: wallet => call("wallet:backup", { wallet }),
  restoreWallet: (wallet) => call("wallet:restore", { wallet }),
  migrateWallet: (wallet, passphrase = "") => call("wallet:migrate", { wallet, passphrase }),
  previewPrivateKey: data => call("wallet:previewPrivateKey", data),
  importPrivateKey: data => call("wallet:importPrivateKey", data),
  importWatchAddress: data => call("wallet:importWatchAddress", data),
  lockAllWallets: () => call("wallet:lockAll"),
  rescanWallet: wallet => call("wallet:rescan", { wallet }),
  abandonTransaction: (wallet, txid) => call("wallet:abandon", { wallet, txid }),
  copy: text => call("clipboard:write", { text }),
  clearClipboardIfMatches: text => call("clipboard:clearIfMatches", { text }),
  openExternal: url => call("external:open", { url }),
  showDataDir: () => call("system:showDataDir"),
  showDebugLog: () => call("system:showDebugLog")
}));
