"use strict";
const T = {
  en: {
    "nav.dashboard":"Dashboard","nav.wallet":"Wallet","nav.send":"Send","nav.receive":"Receive","nav.transactions":"Transactions","nav.network":"Network","nav.backup":"Backup","nav.settings":"Settings",
    "subtitle.dashboard":"Your local VMESH wallet and full node.","subtitle.wallet":"Create, restore and manage Core wallets.","subtitle.send":"Review every payment before Core signs it.","subtitle.receive":"Generate local receive addresses and QR codes.","subtitle.transactions":"Recent wallet activity from VargaMesh Core.","subtitle.network":"Full-node synchronization and peer connectivity.","subtitle.backup":"Core-native wallet backups and recovery.","subtitle.settings":"Language, local files and application information.",
    "node.offline":"Node offline","node.online":"Node online","metric.sync":"Synchronization","metric.peers":"Peers","metric.pending":"Pending","metric.immature":"Immature",
    "quick.title":"Quick actions","quick.receive":"Receive VMESH","quick.send":"Send VMESH","quick.backup":"Back up wallet","quick.refresh":"Refresh",
    "security.title":"Security model","security.body":"Private keys and transaction signing stay inside VargaMesh Core. RPC is local-only and the Electron renderer never receives the RPC cookie.",
    "wallet.create":"Create wallet","wallet.name":"Wallet name","wallet.pass":"Passphrase (recommended)","wallet.passhint":"The passphrase is sent only to local VargaMesh Core and is never stored by Desktop.","wallet.createbtn":"Create wallet","wallet.restore":"Restore existing wallet","wallet.restorebody":"Restore a Core wallet backup without exposing private keys to Electron.","wallet.restorename":"New wallet name","wallet.restorebtn":"Choose backup…","wallet.available":"Wallet directory",
    "send.title":"Send VMESH","send.address":"Recipient address","send.amount":"Amount (VMESH)","send.pass":"Wallet passphrase (only if encrypted)","send.review":"Review transaction","send.confirmTitle":"Confirm irreversible transaction","send.confirmBody":"Transactions cannot be reversed. Verify the recipient and amount carefully.","send.sent":"Transaction broadcast successfully",
    "receive.title":"Receive VMESH","receive.label":"Address label (optional)","receive.generate":"Generate address","receive.qr":"QR code is generated locally. No address is sent to a third party.",
    "tx.title":"Recent transactions","tx.time":"Time","tx.type":"Type","tx.amount":"Amount","tx.confirmations":"Confirmations",
    "network.status":"Node status","network.start":"Start node","network.stop":"Stop node","network.security":"Network / RPC security","network.body":"P2P listens on TCP 29666. RPC is explicitly bound to 127.0.0.1:29667 and should never be forwarded to the Internet.","network.explorer":"Open explorer ↗",
    "backup.title":"Back up selected wallet","backup.body":"Uses Core's backupwallet RPC so the database is copied in a consistent state.","backup.button":"Create wallet backup…","backup.warning":"Critical","backup.warningbody":"Keep multiple offline backups. Never upload a wallet backup or passphrase to a website, chat, issue tracker or cloud service you do not fully trust.",
    "settings.language":"Language","settings.files":"Local files","settings.data":"Open data directory","settings.config":"Open config","settings.about":"About","settings.aboutbody":"Open-source desktop interface for the VargaMesh full node and wallet.",
    "common.copy":"Copy","common.refresh":"Refresh","common.cancel":"Cancel","common.confirm":"Confirm","common.load":"Load","common.unload":"Unload","common.migrate":"Migrate legacy","common.select":"Select",
    "onboard.title":"Your local VMESH node and wallet","onboard.body":"VargaMesh Desktop runs the real Core daemon locally. Wallet keys remain in Core and RPC never leaves localhost.","onboard.continue":"Continue",
    "msg.noWallet":"Create, restore or load a wallet first.","msg.backup":"Wallet backup created.","msg.restore":"Wallet restored successfully.","msg.created":"Wallet created successfully.","msg.migrated":"Legacy wallet migrated. Core created a legacy backup automatically.","msg.copied":"Copied to clipboard."
  },
  de: {
    "nav.dashboard":"Übersicht","nav.wallet":"Wallet","nav.send":"Senden","nav.receive":"Empfangen","nav.transactions":"Transaktionen","nav.network":"Netzwerk","nav.backup":"Sicherung","nav.settings":"Einstellungen",
    "subtitle.dashboard":"Deine lokale VMESH-Wallet und Full Node.","subtitle.wallet":"Core-Wallets erstellen, wiederherstellen und verwalten.","subtitle.send":"Jede Zahlung prüfen, bevor Core sie signiert.","subtitle.receive":"Lokale Empfangsadressen und QR-Codes erzeugen.","subtitle.transactions":"Aktuelle Wallet-Aktivität aus VargaMesh Core.","subtitle.network":"Full-Node-Synchronisierung und Peer-Verbindungen.","subtitle.backup":"Core-native Wallet-Sicherungen und Wiederherstellung.","subtitle.settings":"Sprache, lokale Dateien und App-Informationen.",
    "node.offline":"Node offline","node.online":"Node online","metric.sync":"Synchronisierung","metric.peers":"Peers","metric.pending":"Ausstehend","metric.immature":"Unreif",
    "quick.title":"Schnellaktionen","quick.receive":"VMESH empfangen","quick.send":"VMESH senden","quick.backup":"Wallet sichern","quick.refresh":"Aktualisieren",
    "security.title":"Sicherheitsmodell","security.body":"Private Schlüssel und Transaktionssignaturen bleiben in VargaMesh Core. RPC läuft nur lokal und der Electron-Renderer erhält niemals das RPC-Cookie.",
    "wallet.create":"Wallet erstellen","wallet.name":"Wallet-Name","wallet.pass":"Passphrase (empfohlen)","wallet.passhint":"Die Passphrase wird nur an den lokalen VargaMesh Core übergeben und von Desktop niemals gespeichert.","wallet.createbtn":"Wallet erstellen","wallet.restore":"Bestehende Wallet wiederherstellen","wallet.restorebody":"Core-Wallet-Backup wiederherstellen, ohne private Schlüssel Electron auszusetzen.","wallet.restorename":"Neuer Wallet-Name","wallet.restorebtn":"Backup auswählen…","wallet.available":"Wallet-Verzeichnis",
    "send.title":"VMESH senden","send.address":"Empfängeradresse","send.amount":"Betrag (VMESH)","send.pass":"Wallet-Passphrase (nur bei verschlüsselter Wallet)","send.review":"Transaktion prüfen","send.confirmTitle":"Unwiderrufliche Transaktion bestätigen","send.confirmBody":"Transaktionen können nicht rückgängig gemacht werden. Empfänger und Betrag sorgfältig prüfen.","send.sent":"Transaktion erfolgreich gesendet",
    "receive.title":"VMESH empfangen","receive.label":"Adressbezeichnung (optional)","receive.generate":"Adresse erzeugen","receive.qr":"Der QR-Code wird lokal erzeugt. Die Adresse wird an keinen Drittanbieter gesendet.",
    "tx.title":"Letzte Transaktionen","tx.time":"Zeit","tx.type":"Typ","tx.amount":"Betrag","tx.confirmations":"Bestätigungen",
    "network.status":"Node-Status","network.start":"Node starten","network.stop":"Node stoppen","network.security":"Netzwerk-/RPC-Sicherheit","network.body":"P2P lauscht auf TCP 29666. RPC ist ausdrücklich an 127.0.0.1:29667 gebunden und darf niemals ins Internet weitergeleitet werden.","network.explorer":"Explorer öffnen ↗",
    "backup.title":"Ausgewählte Wallet sichern","backup.body":"Verwendet Cores backupwallet-RPC, damit die Datenbank in konsistentem Zustand kopiert wird.","backup.button":"Wallet-Backup erstellen…","backup.warning":"Wichtig","backup.warningbody":"Mehrere Offline-Backups aufbewahren. Wallet-Backup oder Passphrase niemals in Webseiten, Chats, Issue-Tracker oder nicht vollständig vertrauenswürdige Cloud-Dienste hochladen.",
    "settings.language":"Sprache","settings.files":"Lokale Dateien","settings.data":"Datenordner öffnen","settings.config":"Konfiguration öffnen","settings.about":"Über","settings.aboutbody":"Open-Source-Desktopoberfläche für VargaMesh Full Node und Wallet.",
    "common.copy":"Kopieren","common.refresh":"Aktualisieren","common.cancel":"Abbrechen","common.confirm":"Bestätigen","common.load":"Laden","common.unload":"Entladen","common.migrate":"Legacy migrieren","common.select":"Auswählen",
    "onboard.title":"Deine lokale VMESH-Node und Wallet","onboard.body":"VargaMesh Desktop betreibt den echten Core-Daemon lokal. Wallet-Schlüssel bleiben in Core und RPC verlässt niemals localhost.","onboard.continue":"Weiter",
    "msg.noWallet":"Zuerst eine Wallet erstellen, wiederherstellen oder laden.","msg.backup":"Wallet-Backup wurde erstellt.","msg.restore":"Wallet erfolgreich wiederhergestellt.","msg.created":"Wallet erfolgreich erstellt.","msg.migrated":"Legacy-Wallet migriert. Core hat automatisch ein Legacy-Backup erstellt.","msg.copied":"In die Zwischenablage kopiert."
  }
};

let language="en", settings={}, appInfo={}, nodeState={running:false}, walletState=null, walletList=null, activeView="dashboard";
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const tr=k=>T[language][k]||T.en[k]||k;
function unwrap(r){ if(!r||!r.ok) throw new Error((r&&r.error)||"Operation failed"); return r.data; }
function fmt(n){ const x=Number(n||0); return Number.isFinite(x)?x.toFixed(8):"0.00000000"; }
function toast(msg,error=false){const el=$("#toast");el.textContent=msg;el.className=`toast show${error?" error":""}`;clearTimeout(toast.t);toast.t=setTimeout(()=>el.className="toast",3600);}
function applyI18n(){ document.documentElement.lang=language; $$('[data-i18n]').forEach(el=>{const k=el.dataset.i18n;if(T[language][k])el.textContent=T[language][k];}); $("#langBtn").textContent=language==="de"?"EN":"DE"; updateTitle(); }
function updateTitle(){const map={dashboard:"nav.dashboard",wallet:"nav.wallet",send:"nav.send",receive:"nav.receive",transactions:"nav.transactions",network:"nav.network",backup:"nav.backup",settings:"nav.settings"};$("#pageTitle").textContent=tr(map[activeView]);$("#pageSubtitle").textContent=tr(`subtitle.${activeView}`);}
function showView(name){activeView=name;$$('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===name));updateTitle();if(name==='transactions')refreshTransactions();if(name==='wallet')refreshWallets();if(name==='settings')renderSettings();}
function modal(title,html,confirm){$("#modalTitle").textContent=title;$("#modalBody").innerHTML=html;$("#modal").classList.remove("hidden");$("#modalConfirm").onclick=async()=>{try{await confirm();$("#modal").classList.add("hidden");}catch(e){toast(e.message,true);}};}

async function refreshNode(){try{nodeState=unwrap(await window.vmesh.node.status());const pill=$("#nodePill");pill.classList.toggle("online",!!nodeState.running);pill.classList.toggle("offline",!nodeState.running);pill.querySelector("span").textContent=tr(nodeState.running?"node.online":"node.offline");if(nodeState.running){const pct=Math.max(0,Math.min(100,(nodeState.verificationprogress||0)*100));$("#syncPercent").textContent=`${pct.toFixed(2)}%`;$("#syncBar").style.width=`${pct}%`;$("#heightText").textContent=`${nodeState.blocks} / ${nodeState.headers} blocks`;$("#peerCount").textContent=nodeState.connections??0;$("#peerDetail").textContent=`${nodeState.connections_in||0} in · ${nodeState.connections_out||0} out`;renderNetwork();}}catch(e){nodeState={running:false};}}
async function refreshWallets(){try{walletList=unwrap(await window.vmesh.wallet.list());const sel=$("#walletSelect");sel.innerHTML='<option value="">—</option>';for(const n of walletList.loaded){const o=document.createElement('option');o.value=n;o.textContent=n;sel.appendChild(o);}if(walletList.selected&&walletList.loaded.includes(walletList.selected))sel.value=walletList.selected;else if(walletList.loaded.length===1){await window.vmesh.wallet.select(walletList.loaded[0]);sel.value=walletList.loaded[0];}renderWalletDirectory();await refreshWalletInfo();}catch(e){walletState=null;renderWalletInfo();}}
async function refreshWalletInfo(){try{walletState=unwrap(await window.vmesh.wallet.info());}catch(_){walletState=null;}renderWalletInfo();}
function renderWalletInfo(){if(!walletState){$("#balanceMain").textContent="0.00000000";$("#pendingBalance").textContent="—";$("#immatureBalance").textContent="—";$("#walletNameLabel").textContent="—";return;}const mine=walletState.balances?.mine||{};$("#balanceMain").textContent=fmt(mine.trusted);$("#pendingBalance").textContent=fmt(mine.untrusted_pending);$("#immatureBalance").textContent=fmt(mine.immature);$("#walletNameLabel").textContent=walletState.wallet;}
function renderWalletDirectory(){const box=$("#walletDirectory");box.innerHTML="";if(!walletList)return;for(const w of walletList.available){const loaded=walletList.loaded.includes(w.name);const legacy=(w.warnings||[]).some(x=>/legacy/i.test(x));const row=document.createElement('div');row.className='wallet-entry';const left=document.createElement('div');const strong=document.createElement('strong');strong.textContent=w.name;left.appendChild(strong);if(legacy){const small=document.createElement('small');small.textContent='Legacy wallet';left.appendChild(small);}const btns=document.createElement('div');btns.className='buttons';const select=document.createElement('button');select.textContent=tr('common.select');select.disabled=!loaded;select.onclick=async()=>{unwrap(await window.vmesh.wallet.select(w.name));await refreshWallets();};btns.appendChild(select);const load=document.createElement('button');load.textContent=tr(loaded?'common.unload':'common.load');load.onclick=async()=>{try{if(loaded)unwrap(await window.vmesh.wallet.unload(w.name));else unwrap(await window.vmesh.wallet.load(w.name));await refreshWallets();}catch(e){toast(e.message,true);}};btns.appendChild(load);if(legacy){const mig=document.createElement('button');mig.textContent=tr('common.migrate');mig.onclick=()=>{modal(tr('common.migrate'),`<p>${escapeHtml(w.name)}</p><label>Passphrase (if encrypted)</label><input id="migratePass" type="password" autocomplete="current-password">`,async()=>{unwrap(await window.vmesh.wallet.migrate(w.name,$('#migratePass').value));toast(tr('msg.migrated'));await refreshWallets();});};btns.appendChild(mig);}row.append(left,btns);box.appendChild(row);}}
function renderNetwork(){const d=$("#networkStats");if(!nodeState.running){d.innerHTML='<dt>Status</dt><dd>Offline</dd>';return;}const rows=[["Chain",nodeState.chain],["Height",`${nodeState.blocks} / ${nodeState.headers}`],["Peers",nodeState.connections],["Version",nodeState.subversion],["Protocol",nodeState.protocolversion],["IBD",String(nodeState.initialblockdownload)]];d.innerHTML=rows.map(([a,b])=>`<dt>${escapeHtml(String(a))}</dt><dd>${escapeHtml(String(b))}</dd>`).join('');}
async function refreshTransactions(){const body=$("#txBody");body.innerHTML='<tr><td colspan="5">…</td></tr>';try{const tx=unwrap(await window.vmesh.wallet.transactions());body.innerHTML="";for(const t of [...tx].reverse()){const trEl=document.createElement('tr');const time=t.time?new Date(t.time*1000).toLocaleString(language):'—';const amt=Number(t.amount||0);trEl.innerHTML=`<td>${escapeHtml(time)}</td><td>${escapeHtml(t.category||'')}</td><td class="${amt>=0?'positive':'negative'}">${fmt(amt)}</td><td>${Number(t.confirmations||0)}</td><td><code title="${escapeHtml(t.txid||'')}">${escapeHtml((t.txid||'').slice(0,14))}…</code></td>`;body.appendChild(trEl);}if(!tx.length)body.innerHTML='<tr><td colspan="5">—</td></tr>';}catch(e){body.innerHTML=`<tr><td colspan="5">${escapeHtml(e.message)}</td></tr>`;}}
function renderSettings(){$("#pathInfo").textContent=appInfo.dataDir?`${appInfo.dataDir}\n${appInfo.configFile}`:'';$("#versionLabel").textContent=`v${appInfo.version||'0.1.0'}`;}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}

async function init(){try{appInfo=unwrap(await window.vmesh.app.info());settings=unwrap(await window.vmesh.app.settings());language=settings.language||'en';applyI18n();if(!settings.onboardingDone)$("#onboarding").classList.remove('hidden');await refreshNode();await refreshWallets();renderSettings();setInterval(refreshNode,3000);setInterval(refreshWalletInfo,7000);}catch(e){toast(e.message,true);}}

$$('#nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));$$('[data-go]').forEach(b=>b.onclick=()=>showView(b.dataset.go));$("#langBtn").onclick=async()=>{language=language==='de'?'en':'de';unwrap(await window.vmesh.app.setLanguage(language));applyI18n();};$$('[data-set-lang]').forEach(b=>b.onclick=async()=>{language=b.dataset.setLang;unwrap(await window.vmesh.app.setLanguage(language));applyI18n();});$$('[data-onboard-lang]').forEach(b=>b.onclick=async()=>{language=b.dataset.onboardLang;unwrap(await window.vmesh.app.setLanguage(language));applyI18n();});$("#onboardContinue").onclick=async()=>{unwrap(await window.vmesh.app.finishOnboarding());$("#onboarding").classList.add('hidden');};$("#modalCancel").onclick=()=>$("#modal").classList.add('hidden');
$("#walletSelect").onchange=async e=>{if(e.target.value){unwrap(await window.vmesh.wallet.select(e.target.value));await refreshWalletInfo();}};
$("#createWalletBtn").onclick=async()=>{try{const name=$("#createName").value.trim(),pass=$("#createPass").value;unwrap(await window.vmesh.wallet.create(name,pass));$("#createPass").value='';toast(tr('msg.created'));await refreshWallets();}catch(e){toast(e.message,true);}};
$("#restoreWalletBtn").onclick=async()=>{try{const name=$("#restoreName").value.trim();const r=unwrap(await window.vmesh.wallet.restore(name));if(!r.canceled){toast(tr('msg.restore'));await refreshWallets();}}catch(e){toast(e.message,true);}};
$("#newAddressBtn").onclick=async()=>{try{const address=unwrap(await window.vmesh.wallet.newAddress($("#receiveLabel").value.trim()));$("#receiveAddress").textContent=address;$("#receiveResult").classList.remove('hidden');window.VargaQR.draw($("#qrCanvas"),address,7);}catch(e){toast(e.message,true);}};
$("#copyAddressBtn").onclick=async()=>{const a=$("#receiveAddress").textContent;if(a){unwrap(await window.vmesh.app.copyText(a));toast(tr('msg.copied'));}};
$("#prepareSendBtn").onclick=async()=>{try{const address=$("#sendAddress").value.trim(),amount=$("#sendAmount").value,pass=$("#sendPass").value;const v=unwrap(await window.vmesh.wallet.validateAddress(address));if(!v.isvalid)throw new Error('Invalid address');let fee='';try{const f=unwrap(await window.vmesh.wallet.estimateFee());if(f&&f.feerate)fee=`<p>Estimated network fee rate: <strong>${escapeHtml(String(f.feerate))} VMESH/kvB</strong></p>`;}catch(_){}modal(tr('send.confirmTitle'),`<p>${tr('send.confirmBody')}</p><dl class="stats-list"><dt>Address</dt><dd><code>${escapeHtml(address)}</code></dd><dt>Amount</dt><dd><strong>${escapeHtml(String(amount))} VMESH</strong></dd></dl>${fee}`,async()=>{const txid=unwrap(await window.vmesh.wallet.send(address,amount,pass));$("#sendPass").value='';toast(`${tr('send.sent')}: ${txid}`);await refreshWalletInfo();showView('transactions');});}catch(e){toast(e.message,true);}};
$("#backupBtn").onclick=async()=>{try{const r=unwrap(await window.vmesh.wallet.backup());if(!r.canceled)toast(tr('msg.backup'));}catch(e){toast(e.message,true);}};
$("#refreshBtn").onclick=async()=>{await refreshNode();await refreshWallets();};$("#txRefreshBtn").onclick=refreshTransactions;$("#startNodeBtn").onclick=async()=>{try{unwrap(await window.vmesh.node.start());await refreshNode();}catch(e){toast(e.message,true);}};$("#stopNodeBtn").onclick=async()=>{try{const r=unwrap(await window.vmesh.node.stop());if(r.external)toast('External node was not stopped.');await refreshNode();}catch(e){toast(e.message,true);}};
$("#openDataBtn").onclick=()=>window.vmesh.app.openDataDir();$("#openConfigBtn").onclick=()=>window.vmesh.app.openConfig();$("#websiteBtn").onclick=()=>window.vmesh.app.openWebsite('website');$("#explorerBtn").onclick=()=>window.vmesh.app.openWebsite('explorer');$("#githubBtn").onclick=()=>window.vmesh.app.openWebsite('github');
init();
